### ISSUE TITLE
wont compile...

### ISSUE THREAD

**Issue by utopiaproject2019** [khoih-prog/ESP_WiFiManager_Lite#10]
In file included from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:49:0,
                 from C:\Users\cellu\AppData\Local\Temp\arduino_modified_sketch_401121\defines.h:97,
                 from C:\Users\cellu\AppData\Local\Temp\arduino_modified_sketch_401121\sketch_mar17a.ino:1:
C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:36:10: fatal error: defines.h: No such file or directory
 #include "defines.h"
          ^~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Mega or Mega 2560.

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

The error is so obvious

```
defines.h: No such file or directory
#include "defines.h"
```

I believe you can solve this yourself easily, just requiring some more care of what you'd like to do.

Programming and CS requires **absolute accuracy**, up to every letter, comma, period, thinking, etc.

There are too many wrong things in the post, such as

1. You even post to the wrong library. This is [**ESP_WiFiManager_Lite** library](https://github.com/khoih-prog/ESP_WiFiManager_Lite), not [**ESP_AT_WM_Lite** library](https://github.com/khoih-prog/ESP_AT_WM_Lite)
2. No [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example)

I'm closing this issue now and suggest you to post your basic question on other forum, such as Arduino Forum to ask for basic help.

Good Luck,

**Comment by utopiaproject2019** [comment]
Hi,
Thank you for getting back to me. I added the defines.h file for the mega2560 into the src folder but now gettin getting the following issues...


In file included from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:49:0,                 from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\defines.h:97,                 from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\Mega_ESP8266Shield.ino:13:C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:38:14: error: 'WL_IDLE_STATUS' was not declared in this scope int status = WL_IDLE_STATUS;          // the Wifi radio's status              ^~~~~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:41:1: error: 'ESP8266_AT_WebServer' does not name a type; did you mean 'Esp8266_AT_WM_Lite_h'? ESP8266_AT_WebServer server(80); ^~~~~~~~~~~~~~~~~~~~ Esp8266_AT_WM_Lite_hC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h: In function 'void printWifiStatus()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:47:18: error: 'WiFi' was not declared in this scope   Serial.println(WiFi.localIP());                  ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:50:16: error: 'ssid' was not declared in this scope   Serial.print(ssid);                ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:50:16: note: suggested alternative: 'sin'   Serial.print(ssid);                ^~~~                sinC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:52:18: error: 'pass' was not declared in this scope   Serial.println(pass);                  ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:52:18: note: suggested alternative: 'labs'   Serial.println(pass);                  ^~~~                  labsC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h: In function 'void handleRoot()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:85:35: error: 'SHIELD_TYPE' was not declared in this scope </html>", BOARD_NAME, BOARD_NAME, SHIELD_TYPE, day, hr, min % 60, sec % 60, ++reqCount, analogRead(0));                                   ^~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:85:35: note: suggested alternative: 'BOARD_TYPE' </html>", BOARD_NAME, BOARD_NAME, SHIELD_TYPE, day, hr, min % 60, sec % 60, ++reqCount, analogRead(0));                                   ^~~~~~~~~~~                                   BOARD_TYPEC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:87:3: error: 'server' was not declared in this scope   server.send(200, F("text/html"), temp);   ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:87:3: note: suggested alternative: 'perror'   server.send(200, F("text/html"), temp);   ^~~~~~   perrorC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h: In function 'void handleNotFound()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:95:14: error: 'server' was not declared in this scope   message += server.uri();              ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:95:14: note: suggested alternative: 'perror'   message += server.uri();              ^~~~~~              perrorC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:97:34: error: 'HTTP_GET' was not declared in this scope   message += (server.method() == HTTP_GET) ? F("GET") : F("POST");                                  ^~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h: In function 'void setup()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:119:18: error: 'SHIELD_TYPE' was not declared in this scope   Serial.println(SHIELD_TYPE);                  ^~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:119:18: note: suggested alternative: 'BOARD_TYPE'   Serial.println(SHIELD_TYPE);                  ^~~~~~~~~~~                  BOARD_TYPEC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:120:18: error: 'ESP8266_AT_WEBSERVER_VERSION' was not declared in this scope   Serial.println(ESP8266_AT_WEBSERVER_VERSION);                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:120:18: note: suggested alternative: 'USE_NEW_WEBSERVER_VERSION'   Serial.println(ESP8266_AT_WEBSERVER_VERSION);                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~                  USE_NEW_WEBSERVER_VERSIONC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:125:3: error: 'WiFi' was not declared in this scope   WiFi.init(&EspSerial);   ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:130:24: error: 'WL_NO_SHIELD' was not declared in this scope   if (WiFi.status() == WL_NO_SHIELD)                        ^~~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:138:16: error: 'ssid' was not declared in this scope   Serial.print(ssid);                ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:138:16: note: suggested alternative: 'sin'   Serial.print(ssid);                ^~~~                sinC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:140:18: error: 'pass' was not declared in this scope   Serial.println(pass);                  ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:140:18: note: suggested alternative: 'labs'   Serial.println(pass);                  ^~~~                  labsC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:143:3: error: 'IPAddress' was not declared in this scope   IPAddress localIp(192, 168, 120, 1);   ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:144:17: error: 'localIp' was not declared in this scope   WiFi.configAP(localIp);                 ^~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:148:49: error: 'ENC_TYPE_WPA2_PSK' was not declared in this scope   status = WiFi.beginAP(ssid, AP_channel, pass, ENC_TYPE_WPA2_PSK);                                                 ^~~~~~~~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:155:3: error: 'server' was not declared in this scope   server.on(F("/"), handleRoot);   ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:155:3: note: suggested alternative: 'perror'   server.on(F("/"), handleRoot);   ^~~~~~   perrorC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h: In lambda function:C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:159:5: error: 'server' is not captured     server.send(200, F("text/plain"), F("This works as well"));     ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:157:28: note: the lambda has no capture-default   server.on(F("/inline"), []()                            ^C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:155:3: note: '<typeprefixerror>server' declared here   server.on(F("/"), handleRoot);   ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h: In function 'void setup()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:168:13: error: expected ';' before 'ip'   IPAddress ip = WiFi.localIP();             ^~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:171:18: error: 'ip' was not declared in this scope   Serial.println(ip);                  ^~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h: In function 'void loop()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:181:3: error: 'server' was not declared in this scope   server.handleClient();   ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:181:3: note: suggested alternative: 'perror'   server.handleClient();   ^~~~~~   perrorIn file included from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\defines.h:97:0,                 from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\Mega_ESP8266Shield.ino:13:C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: At global scope:C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:134:32: error: 'IPAddress' does not name a type String IPAddressToString(const IPAddress& _address)                                ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In function 'String IPAddressToString(const int&)':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:136:33: error: invalid types 'const int[int]' for array subscript   String str = String(_address[0]);                                 ^C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:138:27: error: invalid types 'const int[int]' for array subscript   str += String(_address[1]);                           ^C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:140:27: error: invalid types 'const int[int]' for array subscript   str += String(_address[2]);                           ^C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:142:27: error: invalid types 'const int[int]' for array subscript   str += String(_address[3]);                           ^C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: At global scope:C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:447:34: error: 'IPAddress' does not name a type     void setConfigPortalIP(const IPAddress& portalIP = IPAddress(192, 168, 4, 1))                                  ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:480:37: error: 'IPAddress' does not name a type     void setSTAStaticIPConfig(const IPAddress& ip)                                     ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:585:5: error: 'ESP8266_AT_WebServer' does not name a type; did you mean 'Esp8266_AT_WM_Lite_h'?     ESP8266_AT_WebServer* server = NULL;     ^~~~~~~~~~~~~~~~~~~~     Esp8266_AT_WM_Lite_hC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:598:5: error: 'IPAddress' does not name a type     IPAddress portal_apIP = IPAddress(192, 168, 4, 1);     ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:604:5: error: 'IPAddress' does not name a type     IPAddress static_IP   = IPAddress(0, 0, 0, 0);     ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:447:56: error: 'IPAddress' was not declared in this scope     void setConfigPortalIP(const IPAddress& portalIP = IPAddress(192, 168, 4, 1))                                                        ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:447:56: note: suggested alternative: 'ipAddress'     void setConfigPortalIP(const IPAddress& portalIP = IPAddress(192, 168, 4, 1))                                                        ^~~~~~~~~                                                        ipAddressC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In constructor 'ESP_AT_WiFiManager_Lite::ESP_AT_WiFiManager_Lite(Stream*, uint32_t)':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:156:7: error: 'WiFi' was not declared in this scope       WiFi.init(espSerial);       ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:159:28: error: 'WL_NO_SHIELD' was not declared in this scope       if (WiFi.status() == WL_NO_SHIELD)                            ^~~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In member function 'bool ESP_AT_WiFiManager_Lite::connectWiFi(const char*, const char*)':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:179:12: error: 'WiFi' was not declared in this scope       if ( WiFi.begin(ssid, pass) )            ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In member function 'void ESP_AT_WiFiManager_Lite::run()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:341:13: error: 'WiFi' was not declared in this scope         if (WiFi.status() == WL_CONNECTED)             ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:341:30: error: 'WL_CONNECTED' was not declared in this scope         if (WiFi.status() == WL_CONNECTED)                              ^~~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:376:15: error: 'server' was not declared in this scope           if (server)               ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:376:15: note: suggested alternative: 'perror'           if (server)               ^~~~~~               perrorC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In member function 'void ESP_AT_WiFiManager_Lite::setConfigPortalIP(const int&)':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:449:7: error: 'portal_apIP' was not declared in this scope       portal_apIP = portalIP;       ^~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:449:7: note: suggested alternative: 'portalIP'       portal_apIP = portalIP;       ^~~~~~~~~~~       portalIPC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In member function 'void ESP_AT_WiFiManager_Lite::setSTAStaticIPConfig(const int&)':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:482:7: error: 'static_IP' was not declared in this scope       static_IP = ip;       ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:482:7: note: suggested alternative: 'static'       static_IP = ip;       ^~~~~~~~~       staticC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In member function 'String ESP_AT_WiFiManager_Lite::localIP()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:532:37: error: 'WiFi' was not declared in this scope       ipAddress = IPAddressToString(WiFi.localIP());                                     ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In member function 'bool ESP_AT_WiFiManager_Lite::connectToWifi(int)':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1061:25: error: 'WL_IDLE_STATUS' was not declared in this scope       uint8_t status  = WL_IDLE_STATUS;                         ^~~~~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1065:11: error: 'static_IP' was not declared in this scope       if (static_IP != IPAddress(0, 0, 0, 0))           ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1065:11: note: suggested alternative: 'static'       if (static_IP != IPAddress(0, 0, 0, 0))           ^~~~~~~~~           staticC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1065:24: error: 'IPAddress' was not declared in this scope       if (static_IP != IPAddress(0, 0, 0, 0))                        ^~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1065:24: note: suggested alternative: 'ipAddress'       if (static_IP != IPAddress(0, 0, 0, 0))                        ^~~~~~~~~                        ipAddressC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1068:9: error: 'WiFi' was not declared in this scope         WiFi.config(static_IP);         ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1079:18: error: 'WiFi' was not declared in this scope         status = WiFi.begin(ESP8266_AT_config.wifi_ssid, ESP8266_AT_config.wifi_pw);                  ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1082:23: error: 'WL_CONNECTED' was not declared in this scope         if (status == WL_CONNECTED)                       ^~~~~~~~~~~~In file included from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\defines.h:97:0,                 from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\Mega_ESP8266Shield.ino:13:C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In member function 'void ESP_AT_WiFiManager_Lite::handleRequest()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1182:11: error: 'server' was not declared in this scope       if (server)           ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1182:11: note: suggested alternative: 'perror'       if (server)           ^~~~~~           perrorC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h: In member function 'void ESP_AT_WiFiManager_Lite::startConfigurationMode()':C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1358:7: error: 'WiFi' was not declared in this scope       WiFi.configAP(portal_apIP);       ^~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1358:21: error: 'portal_apIP' was not declared in this scope       WiFi.configAP(portal_apIP);                     ^~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1358:21: note: suggested alternative: 'portal_ssid'       WiFi.configAP(portal_apIP);                     ^~~~~~~~~~~                     portal_ssidC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1382:71: error: 'ENC_TYPE_WPA2_PSK' was not declared in this scope       WiFi.beginAP(portal_ssid.c_str(), channel, portal_pass.c_str(), ENC_TYPE_WPA2_PSK, true);                                                                       ^~~~~~~~~~~~~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1384:12: error: 'server' was not declared in this scope       if (!server)            ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1384:12: note: suggested alternative: 'perror'       if (!server)            ^~~~~~            perrorC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1386:22: error: 'ESP8266_AT_WebServer' does not name a type; did you mean 'Esp8266_AT_WM_Lite_h'?         server = new ESP8266_AT_WebServer;                      ^~~~~~~~~~~~~~~~~~~~                      Esp8266_AT_WM_Lite_hC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1393:11: error: 'server' was not declared in this scope       if (server)           ^~~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:1393:11: note: suggested alternative: 'perror'       if (server)           ^~~~~~           perrorC:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\Mega_ESP8266Shield.ino: In function 'void setup()':Mega_ESP8266Shield:65:6: error: redefinition of 'void setup()' void setup()      ^~~~~In file included from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:49:0,                 from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\defines.h:97,                 from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\Mega_ESP8266Shield.ino:13:C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:110:6: note: 'void setup()' previously defined here void setup()      ^~~~~C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\Mega_ESP8266Shield.ino: In function 'void loop()':Mega_ESP8266Shield:131:6: error: redefinition of 'void loop()' void loop()      ^~~~In file included from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/Esp8266_AT_WM_Lite.h:49:0,                 from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\defines.h:97,                 from C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\examples\Mega_ESP8266Shield\Mega_ESP8266Shield.ino:13:C:\Users\cellu\Documents\Arduino\libraries\ESP_AT_WM_Lite-master\src/ESP8266_AT_WebServer.h:179:6: note: 'void loop()' previously defined here void loop()      ^~~~exit status 1redefinition of 'void setup()'







PLEASE HELP.. been struggling with this for several days now.. is it something stupid im missing?? 

Kind Regards

Jay




    On Friday, 18 March 2022, 18:04:09 GMT, Khoi Hoang ***@***.***> wrote:  
 
 


Thanks for your interest in the library.

The error is so obvious
defines.h: No such file or directory
#include "defines.h"

I believe you can solve this yourself easily, just requiring some more care of what you'd like to do.

Programming and CS requires absolute accuracy, up to every letter, comma, period, thinking, etc.

There are too many wrong things in the post, such as
   
   - You even post to the wrong library. This is ESP_WiFiManager_Lite library, not ESP_AT_WM_Lite library
   - No Minimal, Reproducible Example

I'm closing this issue now and suggest you to post your basic question on other forum, such as Arduino Forum to ask for basic help.

Good Luck,

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
