### ISSUE TITLE
Static IP custom parameters

### ISSUE THREAD

**Issue by alexsandro-ss** [khoih-prog/ESP_WiFiManager_Lite#12]
Hello !
Is it possible to add static ip in custom parameters?

**Comment by khoih-prog** [comment]
Anything is possible, provided you know how to store it then use later. The examples are just simple code to demo how to use basic features of any library.

> Is it possible to add static ip in custom parameters?

Treat this as a simple exercise for you.

Please use [**Discussions**](https://github.com/khoih-prog/ESP_WiFiManager_Lite/discussions) next time if not an issue or bug of the library.
