### ISSUE TITLE
LED Status

### ISSUE THREAD

**Issue by MythicalForce** [khoih-prog/ESP_WiFiManager_Lite#2]
### Is your feature request related to a problem? Please describe.

I have so far been unable to change the LED status in the library.

### Describe the solution you'd like
The LED status in this lib is a bit booring and kinda "confusing" so what i wanted todo was

- **LED Off** (nothing is going on / not connected to Wifi)
- **LED Slow Blinking** (Trying to connect to wifi)
- **LED Fast Blinking** (In configuration_mode)
- **LED On** (connected to wifi)

This would make it much better to understand what is going on when Serial Monitor debugging is not possible! :)

### Describe alternatives you've considered
NONE

### Additional context
On my PCB i have a red PWR LED and a blue WIFI LED that i use to indicate the status of the WIFI as described above! but after i switched to this lib i was unable to integrate the LED status above... using Delay() would make the lib go "crazy" spamming the serial monitor with resets and stuff! and using millis would do the same and or sometimes not work at all!

**Comment by khoih-prog** [comment]
Thanks for your interest in the library, which is written to provide basic, **boring** yet important functions to input WiFi Credentials, etc.

It's so simple to add that cosmetic features, but I have no time and interest in doing that. You can easily write the **simple function** to do that to satisfy your interests.

I'm closing the request now.
